name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-24.04
    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"
    
      - name: Show Context Information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Branch: ${{ github.ref }}"
          echo "This workflow was triggered by a ${{ github.event_name }} event."